### ISSUE TITLE
go definition is not curried

### ISSUE THREAD

**Issue by unlocked2412** [RobTrew/prelude-jxa#11]
https://github.com/RobTrew/prelude-jxa/blob/bc566ea066706c83f2e492979e9e60f115455528/jsPrelude.js#L4644

**Comment by unlocked2412** [comment]
Just noticed `find` is called in an uncurried form.

**Comment by RobTrew** [comment]
Good catch. Thanks ! The uncurried use of `find` in `subTreeAtPath` is now fixed.

(The uncurried `go` is, as it happens, by design – currying is generalised in the types of exposed functions, to facilitate composition in user scripts, but not necessarily required for private helper functions within function implementations )

**Comment by RobTrew** [comment]
Closing this for now.
